stages:
- lint
- stop
- deploy
- start

lint:
  stage: lint
  script:
  - yarn run lint
  only:
  - master

stop_rc:
  stage: stop
  script:
  - pm2 stop game-999-server-foundation-tests
  only:
  - pre-production
  allow_failure: true

deploy_rc:
  stage: deploy
  script:
  - rm -rf /gitlab-ci-cd/game-server-foundation
  - cp -r . /gitlab-ci-cd/game-server-foundation
  - chmod -R 755 /gitlab-ci-cd/game-server-foundation
  - cd /gitlab-ci-cd/game-server-foundation
  - yarn
  only:
  - pre-production
  
start_rc:
  stage: start
  script:
  - pm2 start services/999-tests/pm2/rc.json
  only:
  - pre-production
