cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - "node_modules/"

.excepts: &excepts
  except:
    refs:
    - tags
    variables:
    - $CI_COMMIT_MESSAGE =~ /^Release [0-9]+(?:.[0-9]+)+/

stages:
- build
- prepareTest
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - "yarn"
  - "yarn run lint"

init mysql:
  <<: *excepts
  stage: prepareTest
  script:
  - 'mysql -h172.17.56.181 -ugitlab-runner -pgitlab-runner -e"CREATE DATABASE unit_test_${CI_COMMIT_SHORT_SHA} default character set utf8mb4 collate utf8mb4_unicode_ci;"'

test:
  <<: *excepts
  stage: test
  coverage: '/^Lines *: (\d+\.\d+%) \( \d+\/\d+ \)/'
  script:
  - "tsc -p ."
  - "yarn run test"
  artifacts:
    name: coverage
    expire_in: 31d
    paths:
    - coverage/

drop mysql:
  <<: *excepts
  stage: cleanup
  script:
  - 'mysql -h172.17.56.181 -ugitlab-runner -pgitlab-runner -e"DROP DATABASE IF EXISTS unit_test_${CI_COMMIT_SHORT_SHA};"'
