cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - "node_modules/"

.excepts: &excepts
  except:
    refs:
    - tags
#    - /^v[0-9]+(?:.[0-9]+)+/

stages:
- build
- prepareTest
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - "yarn"
  - "yarn run lint"

init mysql:
  <<: *excepts
  stage: prepareTest
  script:
  - 'echo "TODO: init mysql"'

test:
  <<: *excepts
  stage: test
  coverage: '/^Lines *: (\d+\.\d+%) \( \d+\/\d+ \)/'
  script:
  - "yarn run test"
  artifacts:
    name: coverage
    expire_in: 31d
    paths:
    - coverage/

drop mysql:
  <<: *excepts
  stage: cleanup
  script:
  - 'echo "TODO: drop mysql"'
