cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
  - "node_modules/"

.excepts: &excepts
  except:
    refs:
    - tags
    variables:
    - $CI_COMMIT_MESSAGE =~ /^Release [0-9]+(?:.[0-9]+)+/

stages:
- build
- prepareTest
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - "yarn"
  - "yarn run lint"

create database:
  <<: *excepts
  stage: prepareTest
  script:
  - "mysql -h172.17.56.181 -ugitlab-runner -pgitlab-runner -e\"CREATE DATABASE unit_test_$CI_COMMIT_SHORT_SHA default character set utf8mb4 collate utf8mb4_unicode_ci;\""

modify bootstrap-test.yml:
  <<: *excepts
  stage: prepareTest
  script:
  - "sed -i 's/host: 192.168.93.222 # DATABASE_HOST/host: 172.17.56.181/g' test-services/basic/res/bootstrap-test.yml"
  - "sed -i 's/username: mcg # DATABASE_USERNAME/username: gitlab-runner/g' test-services/basic/res/bootstrap-test.yml"
  - "sed -i 's/password: Mcg!2345 # DATABASE_PASSWORD/password: gitlab-runner/g' test-services/basic/res/bootstrap-test.yml"
  - "sed -i 's/database: mcg_games_servers # DATABASE_DATABASE/database: unit_test_$CI_COMMIT_SHORT_SHA/g' test-services/basic/res/bootstrap-test.yml"
  - "cat test-services/basic/res/bootstrap-test.yml"

test:
  <<: *excepts
  stage: test
  coverage: '/^Lines *: (\d+\.\d+%) \( \d+\/\d+ \)/'
  script:
  - "cat test-services/basic/res/bootstrap-test.yml"
  - "tsc -p ."
  - "yarn run test"
  artifacts:
    name: coverage
    expire_in: 31d
    paths:
    - coverage/

drop database:
  <<: *excepts
  stage: cleanup
  script:
  - "mysql -h172.17.56.181 -ugitlab-runner -pgitlab-runner -e\"DROP DATABASE IF EXISTS unit_test_$CI_COMMIT_SHORT_SHA;\""
