stages:
- link
- deploy

lint:
  stage: link
  script:
  - yarn run lint

deploy:rc:
  stage: deploy
  variables:
    DEPLOY_DIR: /gitlab-ci-cd/mcg-rnd/node-server-foundation/${CI_COMMIT_SHORT_SHA}
  script:
  - rm -rf $DEPLOY_DIR
  - mkdir -p $DEPLOY_DIR
  - cp -r . $DEPLOY_DIR
  - chmod -R 755 $DEPLOY_DIR
  - cd $DEPLOY_DIR
  - yarn
  - pm2 start services/tests/pm2-rc.json
  environment:
    name: rc
    url: http://39.106.136.198:29991/graphql
# - /^v[0-9]+(?:.[0-9]+)+/
