cache:
  untracked: true
  key: $CI_PIPELINE_ID
  paths:
  - node_modules/

.excepts: &excepts
  except:
    refs:
    - tags
    variables:
    - $CI_COMMIT_MESSAGE =~ /^Release [0-9]+(?:.[0-9]+)+/

stages:
- build
- prepare
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - yarn
  - yarn run lint

prepare test:
  <<: *excepts
  stage: prepare
  script:
  - . scripts/prepare_test.sh $CI_PIPELINE_ID

test:
  <<: *excepts
  stage: test
  coverage: '/^Lines *: (\d+\.\d+%) \( \d+\/\d+ \)/'
  script:
  - . scripts/modify_config.sh $CI_PIPELINE_ID
  - cat test-services/basic/resource/application-test.yml
  - tsc -p .
  - yarn run test
  artifacts:
    name: coverage
    expire_in: 31d
    paths:
    - coverage/

cleanup test:
  <<: *excepts
  stage: cleanup
  when: always
  script:
  - . scripts/cleanup_test.sh $CI_PIPELINE_ID
