stages:
- build
- test
- cleanup

build:
  stage: build
  script:
  - "yarn"
  - "tsc -p ."

lint:
  stage: test
  script:
  - "yarn run lint"

cleanup:
  stage: cleanup
  script:
  - "echo \"TODO: cleanup\""
