stages:
- build
- test
- cleanup

build:
  stage: build
  script:
  - "yarn"
  except:
  - tags

lint:
  stage: test
  script:
  - "yarn run lint"
  except:
  - tags

cleanup:
  stage: cleanup
  script:
  - "echo \"TODO: cleanup\""
  except:
  - tags
