stages:
- lint
- stop_rc
- deploy_rc

lint_master:
  stage: lint
  script:
  - yarn run lint
  only:
  - master

stop_rc:
  stage: stop_rc
  script:
  - pm2 stop game-999-server-foundation-tests
  only:
  - master
  allow_failure: true

deploy_rc:
  stage: deploy_rc
  script:
  - rm -rf /gitlab-ci-cd/game-server-foundation
  - cp -r . /gitlab-ci-cd/game-server-foundation
  - chmod -R 755 /gitlab-ci-cd/game-server-foundation
  - cd /gitlab-ci-cd/game-server-foundation
  - yarn
  - pm2 start services/Bootstrap.js --name game-999-server-foundation-tests --node-args="rc,foundation:dev 999-foundation-tests"
  only:
  - master
