stages:
- lint
- deploy

lint:
  stage: lint
  script:
  - yarn run lint
  except:
  - master

deploy rc:
  stage: deploy
  script:
  - rm -rf /gitlab-ci-cd/mcg-rnd/node-server-foundation
  - mkdir -p /gitlab-ci-cd/mcg-rnd/node-server-foundation
  - cp -r . /gitlab-ci-cd/mcg-rnd/node-server-foundation
  - chmod -R 755 /gitlab-ci-cd/mcg-rnd/node-server-foundation
  - cd /gitlab-ci-cd/mcg-rnd/node-server-foundation
  - yarn
  - pm2 start services/999-tests/pm2-rc.json
  environment:
    name: rc
    url: http://39.106.136.198:29991/graphql
  only:
  - /^v[0-9]+(?:.[0-9]+)+/
