cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - "node_modules/"
  - "**/*.js"
  - "**/*.js.map"

.excepts: &excepts
  except:
    refs:
    - tags
#    - /^v[0-9]+(?:.[0-9]+)+/
#    changes:
#    - package.json

stages:
- build
- prepareTest
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - "yarn"
#  - "tsc -p ."

init mysql:
  <<: *excepts
  stage: prepareTest
  script:
  - 'echo "TODO: init mysql"'

lint:
  <<: *excepts
  stage: test
  script:
  - "yarn run lint"

test:
  <<: *excepts
  stage: test
  coverage: '/^Lines *: (\d+\.\d+%) \( \d+\/\d+ \)/'
  script:
  - "yarn run test"

drop mysql:
  <<: *excepts
  stage: cleanup
  script:
  - 'echo "TODO: drop mysql"'
