cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - "node_modules/"
  - "./**/*.js"
  - "./**/*.js.map"

.excepts: &excepts
  except:
    refs:
    - /^v[0-9]+(?:.[0-9]+)+/
    changes:
    - package.json

stages:
- build
- prepareTest
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - "yarn"
  - "tsc -p ."

prepareTest:
  <<: *excepts
  stage: prepareTest
  script:
  - "pm2 start tests/Bootstrap.js --name ${CI_COMMIT_SHA}"

lint:
  <<: *excepts
  stage: test
  script:
  - "yarn run lint"

test:
  <<: *excepts
  stage: test
  coverage: '/^Lines *: (\d+\.\d+%) \( \d+\/\d+ \)/'
  script:
  - "yarn run test"

cleanup:
  <<: *excepts
  stage: cleanup
  script:
  - "pm2 stop ${CI_COMMIT_SHA}"
  - "pm2 delete ${CI_COMMIT_SHA}"
