.excepts: &excepts
  except:
  - tags

stages:
- build
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - "yarn"
  - "tsc -p ."

lint:
  <<: *excepts
  stage: test
  script:
  - "yarn run lint"

cleanup:
  <<: *excepts
  stage: cleanup
  script:
  - "echo \"TODO: cleanup\""
