cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/
  - "**/*.js"
  - "**/*.js.map"

.excepts: &excepts
  except:
    refs:
    - /^v[0-9]+(?:.[0-9]+)+/
    changes:
    - package.json

stages:
- build
- test
- cleanup

build:
  <<: *excepts
  stage: build
  script:
  - "yarn"
  - "tsc -p ."

lint:
  <<: *excepts
  stage: test
  script:
  - "yarn run lint"

cleanup:
  <<: *excepts
  stage: cleanup
  script:
  - "echo \"TODO: cleanup\""
