id: "901"
profiles:
- test
configServer:
  type: "local"
server:
  port: 0
data:
  dropTableOnInit: true
  dataSourceMysql:
    host: 39.105.87.12 # DATABASE_HOST
    username: mcg # DATABASE_USERNAME
    password: Mcg!2345 # DATABASE_PASSWORD
    database: test_node_server_foundation # DATABASE_DATABASE
cluster:
  enabled: true
