id: "901"
profiles:
- "dev"
configServer:
  type: "local"
server:
  enabled: true
  httpServerMap:
    primary:
      port: 29011
      graphQLEndpoint: "/graphql"
      webSocketEndpoint: "/ws"
data:
  enabled: true
  databaseMap:
    primary:
      dialect: "mysql"
      host: "39.105.87.12"
      port: 3306
      username: "mcg"
      password: "Mcg!2345"
      database: "dev_node_server_foundation"
      timezone: "Asia/Shanghai"
    secondary:
      dialect: "mysql"
      host: "39.105.87.12"
      port: 3306
      username: "mcg"
      password: "Mcg!2345"
      database: "dev_node_server_foundation_2"
      timezone: "Asia/Shanghai"
cluster:
  enabled: true
