id: "901"
profiles:
- test
configServer:
  type: "local"
server:
  port: -1
cluster:
  enabled: false
data:
  forceSync: true
  dataSourceMysql:
    host: 192.168.93.222 # DATABASE_HOST
    username: mcg # DATABASE_USERNAME
    password: Mcg!2345 # DATABASE_PASSWORD
    database: node_server_foundation_test # DATABASE_DATABASE
