id: "901"
profiles:
- "test"
configServer:
  type: "local"
server:
  enabled: true
  httpServerMap:
    primary:
      port: 0
      graphQLEndpoint: "/graphql"
      webSocketEndpoint: "/ws"
data:
  enabled: true
  databaseMap:
    primary:
      dialect: "mysql"
      host: "39.107.15.85"
      port: 3306
      username: "mcg"
      password: "Mcg!2345"
      database: "test_nsf_1"
      timezone: "Asia/Shanghai"
    secondary:
      dialect: "mysql"
      host: "39.107.15.85"
      port: 3306
      username: "mcg"
      password: "Mcg!2345"
      database: "test_nsf_2"
      timezone: "Asia/Shanghai"
cluster:
  enabled: true
  javaClusterMap:
    oa:
      host: ldev.happyhouse.club
      port: 80
      path: oa
