id: "901"
profiles:
  - "test"
configServer:
  type: "local"
server:
  enabled: true
  httpServerMap:
    primary:
      port: 0
      logError: false
      graphQLEndpoint: "/graphql"
      webSocketEndpoint: "/ws"
cluster:
  enabled: true
  javaClusterMap:
    oa:
      host: ldev.happyhouse.club
      port: 80
      path: oa
